import warnings
from typing import Callable
import numpy.typing as npt
import qgauss
import numpy as np
from scipy.linalg import expm
from scipy.integrate import solve_ivp
from scipy.optimize import fminbound

from ..core.qgstate import QGstate
from ..core.qgoper import QGoper
from ..core.qgsuper import QGsuper
from ..core.tensor import tensor
from ..calc.utilities import *

__all__ = ['unitary_timeevolve','lindblad_timeevolve',
           'moment_timeevolve','backaction_timeevolve']


def unitary_timeevolve(H: QGoper,
                       rho0: QGstate,
                       t: float = 1
                      ) -> QGstate:
    """
    ---- Prodcedure ----
    Apply a unitary operation to QGstate, equivalent to a symplectic-affine 
    transformation. The time evolution is
        ρ(t) = U(t).ρ(0).U*(t) = exp[-i*t*[H,·]].ρ(0)  where  U(t) = exp[-i*H*t].
    This is equivalent to the following evolution of the moments of ρ(0)
        Σ(t) = S(t).Σ(0).S(t)^T,   
        μ(t) = S(t).μ(0) + d(t)
    where for the Hamiltonian H = ½r.H(2).r + r.H(1) + H(0), and A = Ω.H(2),
        S(t) = exp[t*A],    
        d(t) = (1/A).(exp[t*A] - id).(Ω.H(1)).
    For ρ0 with an FLS component, the above expressions are applied individually 
    to each CVS sub-component. These are the exact solutions to the differential 
    equations for the moments:
        dΣ(t)/dt = A.Σ(t) + Σ(t).A^T,
        dμ(t)/dt = A.μ(t) + d(t).
    
    ---- Parameters ----
    H : QGoper
        Time-independent Hamiltonian that will control evolution of the state. 
        Must be CVS only and Hermitian.
    rho0 : QGstate
        Object on which to apply the symplectic-affine transformations.
    t : number
        Time at which to stop calculate the future state. Time starts at t=0, 
        default for the future time is t=1.

    ---- Output ----
    rhof : QGstate
        The state evolved under the Hamiltonian at the give time.
    """
    if H.isfls:
        raise ValueError("Generator of unitary evolution cannot have FLS component.")
    if H.dims_cvs != rho0.dims_cvs:
        raise ValueError("CV component of state and Hamiltonian have different dimensions.")
    
    # Construct elements of the unitary transformation
    _A = H.symform @ H.data_2nd
    _S = expm(t*_A)
    _d = t * expm_int(t*_A) @ (H.symform @ H.data_1st)

    if not rho0.isfls:
        _out_data_2nd = _S @ rho0.data_2nd @ _S.T
        _out_data_1st = _S @ rho0.data_1st + _d
    else:
        _out_data_2nd = np.array([[(_S @ rho0[j,k].data_2nd @ _S.T)
                                   for k in range(rho0.shape_0th[1])]
                                   for j in range(rho0.shape_0th[0])])
        _out_data_1st = np.array([[(_S @ rho0[j,k].data_1st + _d)
                                   for k in range(rho0.shape_0th[1])]
                                   for j in range(rho0.shape_0th[0])])

    return QGstate(data_2nd = _out_data_2nd,
                   data_1st = _out_data_1st,
                   data_0th = rho0.data_0th,
                   dims_fls = rho0.dims_fls,
                   dims_cvs = rho0.dims_cvs)


def lindblad_timeevolve(LV: QGsuper,
                        rho0: QGstate,
                        t: float = 1
                       ) -> QGstate:
    """
    ---- Prodcedure ----
    Calculate future state of initial state under evolution from a 
    time-independent Lindbladian. The time evolution is
        ρ(t) = exp[-t*L(·)].ρ(0) 
    where L is the Lindbladian, which may be expressed as
        L(ρ) = -i*[H,ρ] + sum_{j,k} Γ_jk (r_k.ρ.r_j - ½*[r_j.r_k,ρ]_+), 
        where H = ½r.H(2).r + r.H(1) + H(0)
    This is equivalent to the following evolution of the moments of ρ(0)
        Σ(t) = S(t).Σ(0).S(t)^T + V(t),   
        μ(t) = S(t).μ(0) + d(t)
    where for the given Lindbladian L, A = Ω.(H(2) + Im[Γ]) and C = -Ω.Re[Γ].Ω:
        S(t) = exp[t*A],    
        d(t) = (1/A).(exp[t*A] - id).(Ω.H(1)),
        V(t) = ∫_0^t exp[(t-s)*A].C.exp[(t-s)*A^T] ds
             = inv_vec( ∫_0^t exp[(t-s)*A]⊗exp[(t-s)*A].vec(C) ds)
             = inv_vec( ∫_0^t exp[(t-s)*A⊕A].vec(C) ds) , A⊕B =  A⊗id + id⊗B
             = inv_vec( (1/(A⊕A).(exp[t*A⊕A] - id).vec(C) ).
    In the above "vec" represents the vectorization operation, where "inv_vec" 
    is the inverse function (column or row stacking can be used here since they 
    both transform the Kronecker product to A⊕A). These are the exact solutions 
    to the differential equations for the moments:
        dΣ(t)/dt = A.Σ(t) + Σ(t).A^T + C,
        dμ(t)/dt = A.μ(t) + d(t).

    ---- Parameters ----
    LV : QGoper
        Time-independent Lindbladian that will control evolution of the state. 
        Must be CVS only and CPTP.
    rho0 : QGstate
        Object on which to apply the dynamical transformation generated by 
        the Lindbladian.
    t : number
        Time at which to stop calculate the future state. Time starts at t=0, 
        default for the future time is t=1.

    ---- Output ----
    rhof : QGstate
        The state evolved under the Lindbladian at the give time.
    """
    if LV.isfls:
        raise ValueError("Generator of open-system evolution cannot have FLS component.")
    if LV.dims_cvs != rho0.dims_cvs:
        raise ValueError("CV component of state and Lindbladian have different dimensions.")
    
    # Construct elements of the open-system transformation
    _A = LV.wigner_2nd_rdr
    _C = LV.wigner_2nd_drdr
    _f = LV.wigner_1st_dr
    _S = expm(t*_A)
    _d = t * expm_int(t*_A) @ _f
    _V = vec_to_mat(t * expm_int(t*(np.kron(_A, np.eye(2*LV.dims_cvs)) 
                                    + np.kron(np.eye(2*LV.dims_cvs), _A)))
                    @ mat_to_vec(_C))

    if not rho0.isfls:
        _out_data_2nd = _S @ rho0.data_2nd @ _S.T + _V
        _out_data_1st = _S @ rho0.data_1st + _d
    else:
        _out_data_2nd = np.array([[(_S @ rho0[j,k].data_2nd @ _S.T + _V)
                                   for k in range(rho0.shape_0th[1])]
                                   for j in range(rho0.shape_0th[0])])
        _out_data_1st = np.array([[(_S @ rho0[j,k].data_1st + _d)
                                   for k in range(rho0.shape_0th[1])]
                                   for j in range(rho0.shape_0th[0])])

    return QGstate(data_2nd = _out_data_2nd,
                   data_1st = _out_data_1st,
                   data_0th = rho0.data_0th,
                   dims_fls = rho0.dims_fls,
                   dims_cvs = rho0.dims_cvs)


def moment_timeevolve(L0: QGsuper = None,
                      Lt: list[tuple[QGsuper,Callable[[float], complex]]] = [],
                      rho0: QGstate = None,
                      tlist: list[float] | npt.NDArray[float] = [0,1],
                      elem: tuple[int,int] = None,
                      **options
                     ):
    """
    ---- Procedure ----
    Time-dependent solver for the moments of a state evolving under some
    Liouvillian, which may be time-dependent. The function will output the 
    system state at every time specified in tlist. In case the total dynamics is 
    that of a true-quantum state (CPTP) then it is best that each QGsuper also 
    be CPTP. This check is currently performed on each element of LT, and will 
    influence the choice of solver. If the total dynamics is not CPTP, then the 
    covariance, means, and norm must all be solved simultaneously, increasing 
    the number of variables that must be handled by the ODE solver. 
    
    As an example, the following input will result in the non-norm preserving 
    solver being called since the ladder operators are not-Hermitian, even 
    though together it is just the dynamics of a Hermitian Hamiltonian:
        LT = [[coherent(create()), lambda t: np.exp(1j*np.pi*t/2)] , 
              [coherent(destroy()), lambda t: np.exp(-1j*np.pi*t/2)]].
    The following equivalent statement has no such issue since the QGopers 
    are Hermitian:
        LT = [[coherent(position()), lambda t: np.sqrt(2)*np.cos(np.pi*t/2)] , 
              [coherent(momentum()), lambda t: np.sqrt(2)*np.sin(np.pi*t/2)]]
           = [[coherent(create()+destroy()), lambda t: np.cos(np.pi*t/2)] , 
              [coherent(1j*(create()-destroy())), lambda t: np.sin(np.pi*t/2)]].

    ---- Parameters ----
    L0 : QGsuper
        Time-independent component of the total Lindbladian/Liouvillian. The 
        Liouvillian need not describe the evolution of a true master equation.
    Lt : list[tuple[QGsuper,function]]
        The time-dependent component(s) of the total Lindbladian/Liouvillian. 
        Must be passed as a list of two-element lists or tuples, where the first 
        element is a QGsuper and the section is the function corresponding to 
        the time-dependent coefficient. The function should therefore only 
        accept one argument for the time.
    rho0 : QGstate
        Initial state for the system.
    tlist : list[float]
        List of time values at which to store solutions from the state evolution 
        solver. This must be sorted, and should contain the start and end times. 
        The default initial and final times are t=[0,1].
    elem : tuple[int,int]
        Matrix element of FLS density matrix passed as a tuple. If no variable
        is passed the backaction on all elements are solved if the system has an 
        FLS component, or just the steady-state of the CV system if there is 
        no FLS component.  
    tol : float
        Set tolerance for the magnitude of real or imaginary parts of numbers. 
        Parts of numbers below this tolerance value are set to zero.
    **options : 
        Options to be passed to the ODE solver. All options are listed below.
    atol : float
        Absolute tolerance, default value is settings.atol.
    rtol : float
        Relative tolerance, default value is settings.rtol.
    method : str
        Integration method to be used by Scipy solve_ivp. Due to the data used 
        here, only solvers which can handle complex values will work. The 
        default is ‘RK45’. Other choices for explicit methods are ‘RK23’ and 
        ‘DOP853’, while for implicit solvers the choice is ‘BDF’.

    ---- Returns ----
    rhot : list[QGstate]
        List of QGstates at the times indicated in tlist.
    """
    # --------------------------------------------------------------------------
    _defaults = {'atol': qgauss.settings.atol, 
                 'rtol': qgauss.settings.rtol, 
                 'method': 'RK45'}
    options = {**_defaults, **options}

    # Check and store properties of the total Liouvillian. 
    # If L0 is None, then create an empty QQsuper.
    if L0 is None and Lt != []:
        L0 = QGsuper(dims_cvs = Lt[0][0].dims_cvs, 
                     dims_fls = Lt[0][0].dims_fls)
        
    # If rho0 has no FLS component, and the system is FLS, then create 
    # a list of CVS states.
    if L0.isfls and not rho0.isfls:
        _ones = QGstate(data_0th = np.ones((np.prod(L0.dims_fls[0][0]),
                                            np.prod(L0.dims_fls[0][1]))),
                        dims_fls = L0.dims_fls[0])
        rho0 = tensor(rho0, _ones)

    # --------------------------------------------------------------------------
    # No FLS component is present, solve the CV system.
    if not L0.isfls and L0.iscvs:
        _nt,_mt,_Vt = _moment_timeevolve_solver(L0 = L0,
                                                Lt = Lt,
                                                rho0 = rho0,
                                                tlist = tlist,
                                                **options)
        rhot = [QGstate(data_2nd = _Vt[t],
                        data_1st = _mt[t],
                        data_0th = _nt[t],
                        dims_cvs = L0.dims_cvs)
                for t in range(0, len(tlist))] 
        
    # --------------------------------------------------------------------------
    # Element of the FLS state is specified, solve the corresponding CV component.
    elif L0.isfls and elem is not None:
        _index = np.prod(L0.dims_fls[0][0])*elem[1] + elem[0]

        if L0.issubgauss(_index) and all([x[0].issubgauss(_index) for x in Lt]):
            pass
        else:
            warnings.warn("Evolution of the CV system is not Gaussian. " \
            "Terms which violate this assumption will be ignored.")

        _nt,_mt,_Vt = \
        _moment_timeevolve_solver(L0 = L0[_index,_index],
                                  Lt = [[x[0][_index,_index],x[1]]
                                        for x in Lt],
                                  rho0 = rho0[tuple(elem)],
                                  tlist = tlist,
                                  **options)
        rhot = [QGstate(data_2nd = _Vt[t],
                        data_1st = _mt[t],
                        data_0th = _nt[t],
                        dims_cvs = L0.dims_cvs)
                for t in range(0, len(tlist))] 
        
    # --------------------------------------------------------------------------
    # No element of the FLS state is specified, solve for all components.
    elif L0.isfls and elem is None:
        if L0.isgauss and all([x[0].isgauss for x in Lt]):
            pass
        else:
            warnings.warn("Evolution of the CV system is not Gaussian. " \
            "Terms which violate this assumption will be ignored.")
        
        _fls_row = np.prod(L0.dims_fls[0][0])
        _fls_col = np.prod(L0.dims_fls[0][1])
        _cvs_dim = 2*L0.dims_cvs

        _Vt = np.empty([len(tlist),_fls_row,_fls_col,_cvs_dim,_cvs_dim], dtype=complex)
        _mt = np.empty([len(tlist),_fls_row,_fls_col,_cvs_dim], dtype=complex)
        _nt = np.empty([len(tlist),_fls_row,_fls_col], dtype=complex)

        for _row in range(0,_fls_row):
            for _col in range(0,_fls_col):
                _index = np.prod(L0.dims_fls[0][0])*_col + _row

                _nt[:,_row,_col], _mt[:,_row,_col], _Vt[:,_row,_col] = \
                _moment_timeevolve_solver(L0 = L0[_index,_index],
                                          Lt = [[x[0][_index,_index],x[1]]
                                                for x in Lt],
                                          rho0 = rho0[_row,_col],
                                          tlist = tlist, 
                                          **options)
        rhot = [QGstate(data_2nd = _Vt[t],
                        data_1st = _mt[t],
                        data_0th = _nt[t],
                        dims_cvs = L0.dims_cvs,
                        dims_fls = L0.dims_fls[0])
                for t in range(0, len(tlist))]
        
    return rhot


def _moment_timeevolve_solver(L0: QGsuper,
                              Lt: list[tuple[QGsuper,Callable[[float], complex]]],
                              rho0: QGstate,
                              tlist: list[float] | npt.NDArray[float],
                              **options
                              ):
    """
    ---- Procedure ----
    Helper function for the time-dependent solver. Converts the CVS-only 
    components into systems of coupled ODEs, which are then solved.

    ---- Parameters ----
    L0 : QGsuper
        Time-independent component of the total Lindbladian/Liouvillian.
    Lt : list[tuple[QGsuper,function]]
        The time-dependent component(s) of the total Lindbladian/Liouvillian.
    rho0 : QGstate
        Initial state for the system.
    tlist : list[float]
        List of time values at which to store solutions from the state evolution 
        solver.
    tol : float
        Set tolerance for the magnitude of real or imaginary parts of numbers. 
        Parts of numbers below this tolerance value are set to zero.
    **options : 
        Options to be passed to the ODE solver. All options are listed below.
    atol : float
        Absolute tolerance, default value is settings.atol.
    rtol : float
        Relative tolerance, default value is settings.rtol.
    method : str
        Integration method to be used by Scipy solve_ivp. Due to the data used 
        here, only solvers which can handle complex values will work. The 
        default is ‘RK45’. Other choices for explicit methods are ‘RK23’ and 
        ‘DOP853’, while for implicit solvers the choice is ‘BDF’.

    ---- Returns ----
    cov : array[complex]
        Time-dependent covariance matrix.
    mean : array[complex]
        Time-dependent vector of means.  
    norm : array[complex]
        Time-dependent value of the norm. 
    """
    _defaults = {'atol': qgauss.settings.atol,
                 'rtol': qgauss.settings.rtol, 
                 'method': 'RK45'}
    options = {**_defaults, **options}
    _tol = options['atol']

    # Extract moments from the initial state.
    _dims = rho0.dims_cvs
    _V0 = rho0.data_2nd
    _m0 = rho0.data_1st
    _n0 = rho0.data_0th

    # Extract arrays for the Fokker-Planck equation in Wigner phase-space from 
    # L0 and LT. For the time-dependent component, only save non-zero results.
    if L0 is None:
        _A0 = np.zeros(rho0.shape_2nd)
        _B0 = np.zeros(rho0.shape_2nd)
        _C0 = np.zeros(rho0.shape_2nd)
        _D0 = np.zeros(rho0.shape_1st) 
        _F0 = np.zeros(rho0.shape_1st)
        _G0 = np.zeros(rho0.shape_0th)
    else:
        _A0 = L0.wigner_2nd_rdr
        _B0 = L0.wigner_2nd_rr
        _C0 = L0.wigner_2nd_drdr
        _D0 = L0.wigner_1st_r
        _F0 = L0.wigner_1st_dr
        _G0 = L0.wigner_0th

    if not Lt:
        _At, _Bt, _Ct, _Dt, _Ft, _Gt = [], [], [], [], [], []
    else:
        # Find maximum magnitude element of the time-dependent functions.
        _abs_max = [np.abs(x[1](fminbound(lambda t: -np.abs(x[1](t)), 
                                          tlist[0], tlist[-1]))
                          ) for x in Lt]
        
        # Generate lists of coefficient arrays and time-dependent functions
        # which are large enough to not be excluded from dynamical simulation.
        _At = _tdep_super_array(Lt, 'wigner_2nd_rdr', _abs_max, _tol)
        _Bt = _tdep_super_array(Lt, 'wigner_2nd_rr', _abs_max, _tol)
        _Ct = _tdep_super_array(Lt, 'wigner_2nd_drdr', _abs_max, _tol)
        _Dt = _tdep_super_array(Lt, 'wigner_1st_r', _abs_max, _tol)
        _Ft = _tdep_super_array(Lt, 'wigner_1st_dr', _abs_max, _tol)
        _Gt = _tdep_super_array(Lt, 'wigner_0th', _abs_max, _tol)

    # Check if dynamics of the covariances and means do not preverse the norm of 
    # the state. Pure dissipation is allowed in the form of a non-zer Gt. The 
    # first section will solve the ODEs when the covariances and means are 
    # uncoupled, and the second case will solve them when they are coupled, and 
    # hence need to be handled simultaneously.
    if (np.all(np.abs(_B0) < _tol) 
        and np.all(np.abs(_D0) < _tol)
        and len(_Bt) == 0
        and len(_Dt) == 0
       ):
        _id = np.identity(2*_dims)
        _A0_vec = np.kron(_A0,_id) + np.kron(_id,_A0)
        _At_vec = [[np.kron(x[0],_id) + np.kron(_id,x[0]), x[1]] for x in _At]
        _C0_vec = mat_to_vec(_C0)
        _Ct_vec = [[mat_to_vec(x[0]),x[1]] for x in _Ct]

        def _ode_func_cov(t,X):
            # Function for the vectorized covariance to pass to solve_ivp. 
            #   dΣ(t)/dt = A.Σ(t) + Σ(t).A^T + C
            #-> d/dt vec(Σ(t)) = (I⊗A + A⊗I).vec(Σ(t)) + vec(C)
            _A_vec = _A0_vec + sum([x[0]*x[1](t) for x in _At_vec])
            _C_vec = _C0_vec + sum([x[0]*x[1](t) for x in _Ct_vec])
            return _A_vec @ X + _C_vec
        
        def _ode_func_mean(t,X):
            # Function for the means to pass to solve_ivp.
            #   dμ(t)/dt = A.μ(t) + F
            _A = _A0 + sum([x[0]*x[1](t) for x in _At])
            _F = _F0 + sum([x[0]*x[1](t) for x in _Ft])
            return _A @ X + _F
        
        def _ode_func_norm(t,X):
            # Function for the norm to pass to solve_ivp.
            #   dn(t)/dt = d/dt exp(-v(t)) = exp(-v(t))*(-dv(t)/dt) = -n(t)*G
            _G = _G0 + sum([x[0]*x[1](t) for x in _Gt])
            return -X*_G
        
        _Vsol = solve_ivp(fun = _ode_func_cov, 
                          t_span = (tlist[0],tlist[-1]), 
                          y0 = mat_to_vec(_V0), 
                          t_eval = tlist, 
                          **options)
        _msol = solve_ivp(fun = _ode_func_mean, 
                          t_span = (tlist[0],tlist[-1]), 
                          y0 = _m0, 
                          t_eval = tlist, 
                          **options)
        _nsol = solve_ivp(fun = _ode_func_norm, 
                          t_span = (tlist[0],tlist[-1]), 
                          y0 = _n0, 
                          t_eval = tlist, 
                          **options)

        _Vt = [vec_to_mat(_Vsol.y[:,t]) for t in range(0,len(tlist))]
        _mt = [_msol.y[:,t] for t in range(0,len(tlist))]
        _nt = [_nsol.y[:,t][0] for t in range(0,len(tlist))]

    else:
        # Define single function to pass to solve_ivp which incorporates the 
        # ODEs for all moments. The differential equations are defined as:
        #   dΣ(t)/dt = A.Σ(t) + Σ(t).A^T - Σ(t).B.Σ(t) + C
        #   dμ(t)/dt = (A - B.Σ(t)).μ(t) + F - Σ(t).D
        #   dn(t)/dt = -n(t)*(G + F.μ(t) + ½*μ(t).B.μ(t) + ½*tr[B.Σ(t)])

        # Note: ODE for Σ(t) is not easily vectorized since it is non-linear.
        # The only possible solution is to cast matrix equation as
        #   d/dt [U(t) \\ V(t)] = [[A^T,-B],[-C,-A]].[U(t) \\ V(t)]
        # and then use Σ(t) = V(t).U(t)^-1. This requires more mempory and the
        # matrix inverse, which may be a problem if U(t) is nearly singular.

        def _ode_func_total(t,X):
            _A = _A0 + sum([x[0]*x[1](t) for x in _At])
            _B = _B0 + sum([x[0]*x[1](t) for x in _Bt])
            _C = _C0 + sum([x[0]*x[1](t) for x in _Ct])
            _F = _F0 + sum([x[0]*x[1](t) for x in _Ft])
            _D = _D0 + sum([x[0]*x[1](t) for x in _Dt])
            _G = _G0 + sum([x[0]*x[1](t) for x in _Gt])

            _XV = vec_to_symmat(X[0:_dims*(2*_dims+1)])
            _Xm = X[_dims*(2*_dims+1):_dims*(2*_dims+3)]
            _Xn = X[_dims*(2*_dims+3)]

            return np.concatenate(
                (symmat_to_vec(_A @ _XV + _XV @ _A.T - _XV @ _B @ _XV + _C),
                 (_A - _XV @ _B) @ _Xm + _F - _XV @ _D,
                 -_Xn*(_G + _F @ _Xm + (1/2)*_Xm @ _B @ _Xm + (1/2)*np.trace(_B @ _XV))))

        _X0 = np.concatenate((symmat_to_vec(_V0), _m0, _n0))
        _Xsol = solve_ivp(fun = _ode_func_total, 
                          t_span = (tlist[0],tlist[-1]), 
                          y0 = _X0, 
                          t_eval = tlist, 
                          **options)
        
        _Vt = [vec_to_symmat(_Xsol.y[0:_dims*(2*_dims+1), t]) for t in range(0,len(tlist))]
        _mt = [_Xsol.y[_dims*(2*_dims+1):_dims*(2*_dims+3), t] for t in range(0,len(tlist))]
        _nt = [_Xsol.y[_dims*(2*_dims+3), t] for t in range(0,len(tlist))]

    return _nt,_mt,_Vt


def backaction_timeevolve(L0: QGsuper = None,
                          Lt: list[tuple[QGsuper,Callable[[float], complex]]] = [],
                          rho0: QGstate = None,
                          tlist: list[float] | npt.NDArray[float] = [0,1],
                          elem: tuple[int,int] = None,
                          **options
                         ):
    """
    ---- Procedure ----
    Time domain solver for the backaction rates of a CV system on a specified
    state in a larger finite-level system. The function will automatically 
    check if the evolution is Gaussian, and will raise an error if not. The 
    component of the FLS state can be specified if the system has an FLS 
    component, and if none is given, the backaction on every component will be 
    solved. If the system is only CV, no FLS state need be specified. 
    
    The function will return the total time-integrated dephasing and frequency 
    shift, along with instanteous values of the total dephasing and frequency 
    shift, along with the bare, measurement-induced, and parasitic dephasing 
    subcomponents. Each component of the backaction is stored in a single list, 
    where the first index corresponds to time. In case the rates for the entire 
    FLS state are calculated, the data in the individual time-slices is of the 
    same format as the output of the steady-state function.

    ---- Parameters ----
    L0 : QGsuper
        Time-independent component of the total Lindbladian/Liouvillian. The 
        Liouvillian need not describe the evolution of a true master equation. 
        Must be CVS-only, and so contain no FLS component.
    Lt : list[tuple[QGsuper,function]]
        The time-dependent component(s) of the total Lindbladian/Liouvillian. 
        Must be passed as a list of two-element lists or tuples, where the first 
        element is a QGsuper and the section is the function corresponding to 
        the time-dependent coefficient. The function should therefore only 
        accept one argument for the time.
    rho0 : QGstate
        Initial state for the system. Must be a CVS-only state.
    tlist : list[float]
        List of time values at which to store solutions from the state evolution 
        solver. This must be sorted, and should contain the start and end times. 
        The default initial and final times are t=[0,1].
    tol : float
        Set tolerance for the magnitude of real or imaginary parts of numbers. 
        Parts of numbers below this tolerance value are set to zero.
    elem : tuple[int,int]
        Matrix element of FLS density matrix passed as a tuple. If no variable
        is passed the backaction on all elements are solved if the system has an 
        FLS component, or just the steady-state of the CV system if there is 
        no FLS component.    
    **options : 
        Options to be passed to the ODE solver. All options are listed below.
    atol : float
        Absolute tolerance, default value is settings.atol.
    rtol : float
        Relative tolerance, default value is settings.rtol.
    method : str
        Integration method to be used by Scipy solve_ivp. Due to the data used 
        here, only solvers which can handle complex values will work. The 
        default is 'RK45'. Other choices for explicit methods are 'RK23' and 
        'DOP853', while for implicit solvers the choice is 'BDF'.

    ---- Returns ----
    ba_norm : list[complex] or list[array[complex]]
        Total time-integrated dephasing and frequency shift, as defined by the 
        ratio of the norm with its inital value.
    ba_total : list[complex] or list[array[complex]]
        Steady-state total dephasing and frequency shift.
    ba_bare : list[complex] or list[array[complex]]
        Steady-state parasitic dephasing and frequency shift. Includes 
        components from the innate FLS dynamics as well backation from the 
        CVS state which are independent of the first and second moments.
    ba_meas_ind : list[complex] or list[array[complex]]
        Steady-state measurement induced dephasing and frequency shift. 
        This is the component dependent on the displacement of the 
        continuous variable system.
    ba_para : list[complex] or list[array[complex]]
        Steady-state parasitic dephasing and frequency shift. The dephasing part 
        of this components arises when the CVS state has variances above vacuum,
        while the frequency shift is present even for the vacuum shift.
    """
    # --------------------------------------------------------------------------
    _defaults = {'atol': qgauss.settings.atol, 
                 'rtol': qgauss.settings.rtol, 
                 'method': 'RK45'}
    options = {**_defaults, **options}

    # Check and store properties of the total Liouvillian. 
    # If L0 is None, then create an empty QQsuper.
    if L0 is None and Lt != []:
        L0 = QGsuper(dims_cvs = Lt[0][0].dims_cvs, 
                     dims_fls = Lt[0][0].dims_fls)
        
    # If rho0 has no FLS component, and the system is FLS, then create 
    # a list of CVS states.
    if L0.isfls and not rho0.isfls:
        _ones = QGstate(data_0th = np.ones((np.prod(L0.dims_fls[0][0]),
                                            np.prod(L0.dims_fls[0][1]))),
                        dims_fls = L0.dims_fls[0])
        rho0 = tensor(rho0, _ones)

    # --------------------------------------------------------------------------
    # No FLS component is present, solve the CV system.
    if not L0.isfls and L0.iscvs:
        ba_norm,ba_total,ba_bare,ba_meas_ind,ba_para = \
            _backaction_timeevolve_solver(L0 = L0,
                                          Lt = Lt,
                                          rho0 = rho0,
                                          tlist = tlist,
                                          **options)

    # --------------------------------------------------------------------------
    # Element of the FLS state is specified, solve the corresponding CV component.
    elif L0.isfls and elem is not None:
        _index = np.prod(L0.dims_fls[0][0])*elem[1] + elem[0]

        if L0.issubgauss(_index) and all([x[0].issubgauss(_index) for x in Lt]):
            pass
        else:
            warnings.warn("Evolution of the CV system is not Gaussian. " \
            "Terms which violate this assumption will be ignored.")

        ba_norm,ba_total,ba_bare,ba_meas_ind,ba_para = \
            _backaction_timeevolve_solver(L0 = L0[_index,_index], 
                                          Lt = [[x[0][_index,_index],x[1]] 
                                                for x in Lt], 
                                          rho0 = rho0[tuple(elem)],
                                          tlist = tlist, 
                                          **options)
        
    # --------------------------------------------------------------------------
    # No element of the FLS state is specified, solve for all components.
    elif L0.isfls and elem is None:
        if L0.isgauss and all([x[0].isgauss for x in Lt]):
            pass
        else:
            warnings.warn("Evolution of the CV system is not Gaussian. " \
            "Terms which violate this assumption will be ignored.")
        
        _fls_row = np.prod(L0.dims_fls[0][0])
        _fls_col = np.prod(L0.dims_fls[0][1])

        ba_norm = np.empty([len(tlist),_fls_row,_fls_col], dtype=complex)
        ba_total = np.empty([len(tlist),_fls_row,_fls_col], dtype=complex)
        ba_bare = np.empty([len(tlist),_fls_row,_fls_col], dtype=complex)
        ba_meas_ind = np.empty([len(tlist),_fls_row,_fls_col], dtype=complex)
        ba_para = np.empty([len(tlist),_fls_row,_fls_col], dtype=complex)

        for _row in range(0,_fls_row):
            for _col in range(0,_fls_col):
                _index = np.prod(L0.dims_fls[0][0])*_col + _row

                (ba_norm[:,_row,_col], 
                 ba_total[:,_row,_col], 
                 ba_bare[:,_row,_col], 
                 ba_meas_ind[:,_row,_col], 
                 ba_para[:,_row,_col]) = \
                    _backaction_timeevolve_solver(L0 = L0[_index,_index], 
                                                  Lt = [[x[0][_index,_index],x[1]]
                                                        for x in Lt], 
                                                  rho0 = rho0[_row,_col], 
                                                  tlist = tlist, 
                                                  **options)
                
    return ba_norm,ba_total,ba_bare,ba_meas_ind,ba_para

 
def _backaction_timeevolve_solver(L0: QGsuper,
                                  Lt: list[tuple[QGsuper,Callable[[float], complex]]],
                                  rho0: QGstate,
                                  tlist: list[float] | npt.NDArray[float],
                                  **options
                                 ):
    """
    The backaction on an operator ρ is defined as tr[ρ] = exp[-v]. The 
    backaction rate is then extracted from dv/dt, defined by
        dv/dt = G + μ.D + (1/2)*μ.B.μ + (1/2)*trace[B.Σ]
    where Σ and μ are the 2nd and 1st central moments of ρ, respectively. The 
    elements B,D,G are extracted from the 'input' Liouvillian with governs the 
    dynamics of ρ. The dephasing rate and frequency shift correspond to the real 
    and imaginary parts of 'v', respectively. The backaction may be broken into 
    bare/innate 'ba_bare', measurement induced 'ba_meas_ind', and parasitic 
    'ba_para', components:
        bare = G
        meas_ind = μ.D + (1/2)*μ.B.μ
        para = (1/2)*trace[B.Σ]

    ---- Parameters ----
    L0 : QGsuper
        Time-independent QGsuper whose steady-state is to be solved, and the 
        backaction extracted. Must be CVS-only.
    tol : float
        Set tolerance for the magnitude of real or imaginary parts of numbers.
        Parts of numbers below this tolerance value are set to zero.
    
    ---- Returns ----
    ba_norm : array[complex]
    ba_total : array[complex]
    ba_bare : array[complex]
    ba_meas_ind : array[complex]
    ba_para : array[complex]

    Which is the better output format:
    # -> tuple[list[complex],list[complex],list[complex],list[complex],list[complex]] (currently used)
    # -> list[tuple[complex,complex,complex,complex,complex]]
    """
    # Solve the dynamics of the moments of the initial state rho0 evolving under 
    # the Lindbladian QGsuper L0 + Lt.
    _nt,_mt,_Vt = _moment_timeevolve_solver(L0 = L0,
                                            Lt = Lt,
                                            rho0 = rho0,
                                            tlist = tlist,
                                            **options)
    _tol = options['atol']

    if L0 is None:
        _B0 = np.zeros(rho0.shape_2nd)
        _D0 = np.zeros(rho0.shape_1st)
        _G0 = np.zeros(rho0.shape_0th)
    else:
        _B0 = L0.wigner_2nd_rr
        _D0 = L0.wigner_1st_r
        _G0 = L0.wigner_0th

    if not Lt:
        _Bt, _Dt, _Gt = [], [], []
    else:
        _abs_max = [np.abs(x[1](fminbound(lambda t: -np.abs(x[1](t)), 
                                tlist[0], tlist[-1]))
                          ) for x in Lt]
        _Bt = _tdep_super_array(Lt, 'wigner_2nd_rr', _abs_max, _tol)
        _Dt = _tdep_super_array(Lt, 'wigner_1st_r', _abs_max, _tol)
        _Gt = _tdep_super_array(Lt, 'wigner_0th', _abs_max, _tol)

    ba_norm = np.empty([len(tlist)], dtype=complex)    
    ba_total = np.empty([len(tlist)], dtype=complex)
    ba_bare = np.empty([len(tlist)], dtype=complex)
    ba_meas_ind = np.empty([len(tlist)], dtype=complex)
    ba_para = np.empty([len(tlist)], dtype=complex)

    # Calculate the parasitic and measurement induced parts of the backaction.
    for u in range(0,len(tlist)):
        _B = _B0 + sum([x[0]*x[1](tlist[u]) for x in _Bt])
        _D = _D0 + sum([x[0]*x[1](tlist[u]) for x in _Dt])
        _G = _G0 + sum([x[0]*x[1](tlist[u]) for x in _Gt])

        ba_norm[u] = _nt[u] / _nt[0]
        ba_bare[u] = _G[0]
        ba_meas_ind[u] = _mt[u] @ _D + (1/2)*_mt[u] @ _B @ _mt[u]
        ba_para[u] = (1/2)*np.trace(_B @ _Vt[u])
        ba_total[u] = ba_bare[u] + ba_meas_ind[u] + ba_para[u]

    return ba_norm,ba_total,ba_bare,ba_meas_ind,ba_para


def _tdep_super_array(data : list[tuple[QGsuper,Callable[[float], complex]]],
                      prop : str,
                      abs : list[float],
                      tol : float = qgauss.settings.atol
                     ) -> list[tuple[npt.NDArray,Callable[[float], complex]]]:
    """
    From a list of QGsuper elements and time-dependent functions, generate a 
    list of arrays for the specified component "prop" of the Wigner Gaussian 
    dynamics and time-dependent functions. Will ignore arrays where all elements 
    multiplied by maximum absolute value of the time-dependent function, are 
    below the tolerance, and are effectively zero.
    """
    return [[getattr(x[0], prop), x[1]]
            for x,y in zip(data,abs)
            if not np.all(np.abs(y*getattr(x[0], prop)) < tol)]