import warnings
import numpy.typing as npt
import qgauss
import numpy as np
from scipy.linalg import eigvals,solve,solve_continuous_lyapunov

from .qgstate import QGstate
from .qgsuper import QGsuper

__all__ = ['moment_steadystate','backaction_steadystate']


def moment_steadystate(L0: QGsuper,
                       tol: float = qgauss.settings.atol
                      ) -> QGstate:
    """
    Steady-state solver for the steady-state for a corresponding CV system 
    Liouvillian, L0. The function will exit if it is found that no steady-state 
    solution to L0 exists.

    ---- Parameters ----
    L0 : QGsuper
        System Lindbladian/Liouvillian. The Liouvillian need not describe the 
        evolution of a true master equation. Must be CVS-only, and so contain 
        no FLS component.
    tol : float
        Set tolerance for the magnitude of real or imaginary parts of numbers. 
        Parts of numbers below this tolerance value are set to zero.

    ---- Returns ----
    rhof : QGstate
        Steady-state intracavity state associated with the input superoperator.
    """

    # Generate arrays
    """
    Generate arrays for the moment equations. These are the arrays obtained by
    mapping the Liouvillian to a partial differential equation in the Wigner
    phase space of the form, where W(r;t) is the Wigner function
        ∂W(r;t)/∂t = (-G - (∂/∂r).F - r.D 
                       + ½*(∂/∂r).C.(∂/∂r) - ½*r.B.r - (∂/∂r).A.r) W(r;t)
    """
    _A = L0.wigner_2nd_rdr
    _B = L0.wigner_2nd_rr
    _C = L0.wigner_2nd_drdr
    _D = L0.wigner_1st_r
    _F = L0.wigner_1st_dr

    # Check if system is stable before proceeding
    if not all(np.real(x) < 0 for x in eigvals(_A)):
        warnings.warn("System has eigenvalues with positive real part and " \
        "is therefore unstable: no steady-state solution exists. " \
        "Program will proceed, but results will not be physically valid.")

    # Solve steady-state moment equations generated by the arrays
    if (np.all(np.abs(_B) < tol) and np.all(np.abs(_D) < tol)):
        """
        Solver for the steady-state of a norm-preserving Liouvillian. This 
        solver converts the input data into the following matrix equations:
            0 = Σ.A^T + Σ.V + C
            0 = A.μ + F
        Σ is the covariance matrix, and μ is an array containing the means.
        A Scipy function is used here to solve the Lyapunov equation for the 
        covariance matrix.
        """
        # Solve covariance matrix
        _cov = solve_continuous_lyapunov(_A,-_C)
        # Solve means
        _mean = solve(_A,-_F)

    else:
        """
        Solver for the steady-state of a non-norm-preserving Liouvillian. This 
        solver converts the input data into the following non-linear matrix 
        equations:
            0 = A.Σ + Σ.A^T - Σ.B.Σ + C
            0 = (A - B.Σ).μ + F - Σ.D
        Σ is the covariance matrix, and μ is an array containing the means. For 
        the covariance matrix, the continuous algebraic Riccati equation (CARE) 
        is solved using the stable-subspace solution method.
        """
        # Solve covariance matrix using the "Hamiltonian" matrix, or H-matrix
        _H = np.block([[_A.T, -_B], [-_C, -_A]])
        _evals, _evecs = np.linalg.eig(_H)

        # Vector of stable eigenvalues               
        _stbl = np.where(np.real(_evals) < 0)[0]          
        if len(_stbl) != 2*L0.dims_cvs:
            # Terminate program if dimensions of stable subspace are too small or large
            raise ValueError("No stable solution can be found for the covariance matrix.")

        # Array of stable eigenvectors
        _soln = _evecs[:,_stbl]                           
        _cov = (_soln[2*L0.dims_cvs:4*L0.dims_cvs,0:2*L0.dims_cvs] 
                @ np.linalg.inv(_soln[0:2*L0.dims_cvs,0:2*L0.dims_cvs]))
        # Solve means
        _mean = solve(_A - _cov @ _B,-_F + _cov @ _D)

    rhof = QGstate(data_2nd = _cov,
                   data_1st = _mean,
                   dims_cvs = L0.dims_cvs)
    return rhof


def backaction_steadystate(L0: QGsuper,
                           elem: str = None,
                           tol: float = qgauss.settings.atol
                          ) -> tuple[complex,complex,complex,complex] | \
                           tuple[npt.NDArray[complex],npt.NDArray[complex],
                                 npt.NDArray[complex],npt.NDArray[complex]] :
    """
    ---- Procedure ----
    Steady-state solver for the backaction rates of a CV system on a 
    finite-level system. The function will automatically check if the evolution 
    is Gaussian, and will raise an error if not. The function will also check if 
    a steady-state exists and will exit if not. The component of the FLS state 
    can be specified if the system has an FLS component, and if none is given, 
    the backaction on every component will be solved. If the system is only CV, 
    no FLS state need be specified. The function will return the total dephasing 
    and frequency shift, along with the bare, measurement-induced, and parasitic 
    dephasing subcomponents. 

    ---- Parameters ----
    L0 : QGsuper
        System Lindbladian/Liouvillian. The Liouvillian need not describe the 
        evolution of a true master equation.
    elem : tuple[int,int]
        Matrix element of FLS density matrix passed as a tuple. If no variable
        is passed the backaction on all elements are solved if the system has an 
        FLS component, or just the steady-state of the CV system if there is 
        no FLS component.
    tol : float
        Set tolerance for the magnitude of real or imaginary parts of numbers. 
        Parts of numbers below this tolerance value are set to zero.

    ---- Returns ----
    ba_total : complex or array[complex]
        Steady-state total dephasing and frequency shift.
    ba_bare : complex or array[complex]
        Steady-state parasitic dephasing and frequency shift. Includes 
        components from the innate FLS dynamics as well backation from the 
        CVS state which are independent of the first and second moments.
    ba_meas_ind : complex or array[complex]
        Steady-state measurement induced dephasing and frequency shift. This is 
        the component dependent on the displacement of the continuous variable 
        system.
    ba_para : complex or array[complex]
        Steady-state parasitic dephasing and frequency shift. The dephasing part 
        of this components arises when the CVS state has variances above vacuum, 
        while the frequency shift is present even for the vacuum shift.
    """
    # ----------------------------------------------------------------------
    # No FLS component is present, solve the CV system
    if not L0.isfls and L0.iscvs:
        ba_total,ba_bare,ba_meas_ind,ba_para = \
            _backaction_steadystate_solver(L0, tol)

    # ----------------------------------------------------------------------
    # Element of the FLS state is specified, solve the corresponding CV component
    elif L0.isfls and elem is not None:
        # Index for the element of the superoperator which acts on the FLS state
        _index = np.prod(L0.dims_fls[0][0])*elem[1] + elem[0]

        # Check if system evolution preserves the Gaussian state
        if L0.issubgauss(_index):
            pass
        else:
            warnings.warn("Evolution of the CV system is not Gaussian." \
            "Terms which violate this assumption will be ignored.")

        ba_total,ba_bare,ba_meas_ind,ba_para = \
            _backaction_steadystate_solver(L0[_index,_index], tol)

    # ----------------------------------------------------------------------
    # No element of the FLS state is specified, solve for all components
    elif L0.isfls and elem is None:
        # Check if system evolution preserves the Gaussian state
        if L0.isgauss:
            pass
        else:
            warnings.warn("Evolution of the CV system is not Gaussian." \
            "Terms which violate this assumption will be ignored.")
        
        _row_total = np.prod(L0.dims_fls[0][0])
        _col_total = np.prod(L0.dims_fls[0][1])

        ba_total = np.empty([_row_total,_col_total], dtype=complex)
        ba_bare = np.empty([_row_total,_col_total], dtype=complex)
        ba_meas_ind = np.empty([_row_total,_col_total], dtype=complex)
        ba_para = np.empty([_row_total,_col_total], dtype=complex)

        for _row in range(0,_row_total):
            for _col in range(0,_col_total): 
                _index = np.prod(L0.dims_fls[0][0])*_col + _row
            
                (ba_total[_row,_col], ba_bare[_row,_col], 
                 ba_meas_ind[_row,_col], ba_para[_row,_col]) = \
                    _backaction_steadystate_solver(L0[_index,_index], tol)

    return ba_total,ba_bare,ba_meas_ind,ba_para


def _backaction_steadystate_solver(L0: QGsuper,
                                   tol: float
                                  ) -> tuple[complex,complex,complex,complex]:
    """
    The backaction on an operator ρ is defined as tr[ρ] = exp[-v]. The 
    backaction rate is then extracted from dv/dt, defined by
        dv/dt = G + μ.D + (1/2)*μ.B.μ + (1/2)*trace[B.Σ]
    where Σ and μ are the 2nd and 1st central moments of ρ, respectively. The 
    elements B,D,G are extracted from the L0 Liouvillian with governs the 
    dynamics of ρ. The dephasing rate and frequency shift correspond to the real 
    and imaginary parts of 'v', respectively. The backaction may be broken into 
    bare/innate 'ba_bare', measurement induced 'ba_meas_ind', and parasitic 
    'ba_para', components:
        bare = G
        meas_ind = μ.D + (1/2)*μ.B.μ
        para = (1/2)*trace[B.Σ]

    ---- Parameters ----
    L0 : QGsuper
        System QGsuper whose steady-state is to be solved, and the backaction 
        extracted. Must be CVS-only.
    tol : float
        Set tolerance for the magnitude of real or imaginary parts of numbers. 
        Parts of numbers below this tolerance value are set to zero.
    
    ---- Returns ----
    ba_total : complex
    ba_bare : complex
    ba_meas_ind : complex
    ba_para : complex
    """
    # Solve the steady-state of the system evolving under L0 QGsuper
    rhof = moment_steadystate(L0, tol)

    # Generate arrays from the L0 QGsuper
    _B = L0.wigner_2nd_rr
    _D = L0.wigner_1st_r
    _G = L0.wigner_0th[0]

    # Calculate the parasitic and measurement induced parts of the backaction
    ba_bare = _G
    ba_meas_ind = rhof.data_1st @ _D + (1/2)*rhof.data_1st @ _B @ rhof.data_1st
    ba_para = (1/2)*np.trace(_B @ rhof.data_2nd)
    ba_total = ba_bare + ba_meas_ind + ba_para

    return ba_total,ba_bare,ba_meas_ind,ba_para