import sys
import warnings
import types
import typing
import numbers
import numpy.typing as npt

import qgauss
import numpy as np
from scipy import linalg as la

from .qgstate import *
from .qgoper import *
from .qgsuper import *
from .fn_utilities import *

__all__ = ['unitary_timeevolve','lindblad_timeevolve']


def unitary_timeevolve(rho0: QGstate,
                       H: QGoper,
                       t: float = 1
                       ) -> QGstate:
    """
    ---- Prodcedure ----
    Apply a unitary operation to QGstate, equivalent to a symplectic-affine transformation. The time evolution is
        ρ(t) = U(t).ρ(0).U*(t) = exp[-i*t*[H,·]].ρ(0)  where  U(t) = exp[-i*H*t].
    This is equivalent to the following evolution of the moments of ρ(0)
        Σ(t) = S(t).Σ(0).S(t)^T,   
        μ(t) = S(t).μ(0) + d(t)
    where for the Hamiltonian H = ½r.H(2).r + r.H(1) + H(0), and A = Ω.H(2),
        S(t) = exp[t*A],    
        d(t) = (1/A).(exp[t*A] - id).(Ω.H(1)).
    For ρ0 with an FLS component, the above expressions are applied individually to each CVS sub-component. These are 
    the exact solutions to the differential equations for the moments:
        dΣ(t)/dt = A.Σ(t) + Σ(t).A^T,
        dμ(t)/dt = A.μ(t) + d(t).
    
    ---- Parameters ----
    rho0 : QGstate
        Object on which to apply the symplectic-affine transformations.
    H : QGoper
        Time-independent Hamiltonian that will control evolution of the state. Must be CVS only and Hermitian.
    t : number
        Time at which to stop calculate the future state. Time starts at t=0, default for the future time is t=1.

    ---- Output ----
    output : QGstate
        The state evolved under the Hamiltonian at the give time.
    """
    if H.isfls:
        raise ValueError("Generator of unitary evolution cannot have FLS component.")
    if H.dims_cvs != rho0.dims_cvs:
        raise ValueError("CV component of state and Hamiltonian have different dimensions.")
    
    # Construct elements of the unitary transformation
    A = H.symform @ H.data_2nd
    S = la.expm(t*A)
    d = t * exp_integrator_phi_function(t*A) @ (H.symform @ H.data_1st)

    if not rho0.isfls:
        out_data_2nd = S @ rho0.data_2nd @ np.transpose(S)
        out_data_1st = S @ rho0.data_1st + d
    else:
        out_data_2nd = np.array([[(S @ rho0[j,k].data_2nd @ np.transpose(S))
                                  for k in range(rho0.shape_0th[1])]
                                  for j in range(rho0.shape_0th[0])])
        out_data_1st = np.array([[(S @ rho0[j,k].data_1st + d)
                                  for k in range(rho0.shape_0th[1])]
                                  for j in range(rho0.shape_0th[0])])

    return QGstate(data_2nd = out_data_2nd,
                   data_1st = out_data_1st,
                   data_0th = rho0.data_0th,
                   dims_fls = rho0.dims_fls,
                   dims_cvs = rho0.dims_cvs
                   )    


def lindblad_timeevolve(rho0: QGstate,
                        L: QGsuper,
                        t: float = 1
                        ) -> QGstate:
    """
    ---- Prodcedure ----
    Calculate future state of initial state under evolution from a time-independent Lindbladian. The time evolution is
        ρ(t) = exp[-t*L(·)].ρ(0) 
    where L is the Lindbladian, which may be expressed as
        L(ρ) = -i*[H,ρ] + sum_{j,k} Γ_jk (r_k.ρ.r_j - ½*[r_j.r_k,ρ]_+), where H = ½r.H(2).r + r.H(1) + H(0)
    This is equivalent to the following evolution of the moments of ρ(0)
        Σ(t) = S(t).Σ(0).S(t)^T + V(t),   
        μ(t) = S(t).μ(0) + d(t)
    where for the given Lindbladian L, A = Ω.(H(2) + Im[Γ]) and C = -Ω.Re[Γ].Ω:
        S(t) = exp[t*A],    
        d(t) = (1/A).(exp[t*A] - id).(Ω.H(1)),
        V(t) = ∫_0^t exp[(t-s)*A].C.exp[(t-s)*A^T] ds
             = inv_vec( ∫_0^t exp[(t-s)*A]⊗exp[(t-s)*A].vec(C) ds)
             = inv_vec( ∫_0^t exp[(t-s)*A⊕A].vec(C) ds)  where  A⊕B =  A⊗id + id⊗B
             = inv_vec( (1/(A⊕A).(exp[t*A⊕A] - id).vec(C) ).
    In the above "vec" represents the vectorization operation, where "inv_vec" is the inverse function (column or row 
    stacking can be used here since they both transform the Kronecker product to A⊕A). These are the exact solutions to 
    the differential equations for the moments:
        dΣ(t)/dt = A.Σ(t) + Σ(t).A^T + C,
        dμ(t)/dt = A.μ(t) + d(t).

    ---- Parameters ----
    rho0 : QGstate
        Object on which to apply the dynamical transformation generated by the Lindbladian.
    L : QGoper
        Time-independent Lindbladian that will control evolution of the state. Must be CVS only and CPTP.
    t : number
        Time at which to stop calculate the future state. Time starts at t=0, default for the future time is t=1.

    ---- Output ----
    output : QGstate
        The state evolved under the Lindbladian at the give time.
    """
    if L.isfls:
        raise ValueError("Generator of open-system evolution cannot have FLS component.")
    if L.dims_cvs != rho0.dims_cvs:
        raise ValueError("CV component of state and Lindbladian have different dimensions.")
    
    # Construct elements of the open-system transformation
    A = L.wigner_2nd_deriv_var
    C = L.wigner_2nd_deriv
    f = L.wigner_1st_deriv
    S = la.expm(t*A)
    d = t * exp_integrator_phi_function(t*A) @ f
    V = np.reshape(t * exp_integrator_phi_function(t*(la.kron(A,np.eye(2*L.dims_cvs)) 
                                                       + la.kron(np.eye(2*L.dims_cvs),A)
                                                       ))
                                                       @ C.ravel(order="C"), L.shape_2nd, order="C")

    if not rho0.isfls:
        out_data_2nd = S @ rho0.data_2nd @ np.transpose(S) + V
        out_data_1st = S @ rho0.data_1st + d
    else:
        out_data_2nd = np.array([[(S @ rho0[j,k].data_2nd @ np.transpose(S) + V)
                                  for k in range(rho0.shape_0th[1])]
                                  for j in range(rho0.shape_0th[0])])
        out_data_1st = np.array([[(S @ rho0[j,k].data_1st + d)
                                  for k in range(rho0.shape_0th[1])]
                                  for j in range(rho0.shape_0th[0])])

    return QGstate(data_2nd = out_data_2nd,
                   data_1st = out_data_1st,
                   data_0th = rho0.data_0th,
                   dims_fls = rho0.dims_fls,
                   dims_cvs = rho0.dims_cvs
                   )