import sys
from typing import Callable
import numpy.typing as npt
import qgauss
import numpy as np
from scipy import linalg as la
from scipy.integrate import solve_ivp

from .qgstate import QGstate
from .qgoper import QGoper
from .qgsuper import QGsuper
from .fn_tensor import tensor
from .fn_utilities import *

__all__ = ['unitary_timeevolve','lindblad_timeevolve',
           'moment_timeevolve','backaction_timeevolve']


def unitary_timeevolve(H: QGoper,
                       rho0: QGstate,
                       t: float = 1
                       ) -> QGstate:
    """
    ---- Prodcedure ----
    Apply a unitary operation to QGstate, equivalent to a symplectic-affine transformation. The time evolution is
        ρ(t) = U(t).ρ(0).U*(t) = exp[-i*t*[H,·]].ρ(0)  where  U(t) = exp[-i*H*t].
    This is equivalent to the following evolution of the moments of ρ(0)
        Σ(t) = S(t).Σ(0).S(t)^T,   
        μ(t) = S(t).μ(0) + d(t)
    where for the Hamiltonian H = ½r.H(2).r + r.H(1) + H(0), and A = Ω.H(2),
        S(t) = exp[t*A],    
        d(t) = (1/A).(exp[t*A] - id).(Ω.H(1)).
    For ρ0 with an FLS component, the above expressions are applied individually to each CVS sub-component. These are 
    the exact solutions to the differential equations for the moments:
        dΣ(t)/dt = A.Σ(t) + Σ(t).A^T,
        dμ(t)/dt = A.μ(t) + d(t).
    
    ---- Parameters ----
    H : QGoper
        Time-independent Hamiltonian that will control evolution of the state. Must be CVS only and Hermitian.
    rho0 : QGstate
        Object on which to apply the symplectic-affine transformations.
    t : number
        Time at which to stop calculate the future state. Time starts at t=0, default for the future time is t=1.

    ---- Output ----
    rhof : QGstate
        The state evolved under the Hamiltonian at the give time.
    """
    if H.isfls:
        raise ValueError("Generator of unitary evolution cannot have FLS component.")
    if H.dims_cvs != rho0.dims_cvs:
        raise ValueError("CV component of state and Hamiltonian have different dimensions.")
    
    # Construct elements of the unitary transformation
    A = H.symform @ H.data_2nd
    S = la.expm(t*A)
    d = t * exp_integrator_phi_function(t*A) @ (H.symform @ H.data_1st)

    if not rho0.isfls:
        out_data_2nd = S @ rho0.data_2nd @ np.transpose(S)
        out_data_1st = S @ rho0.data_1st + d
    else:
        out_data_2nd = np.array([[(S @ rho0[j,k].data_2nd @ np.transpose(S))
                                  for k in range(rho0.shape_0th[1])]
                                  for j in range(rho0.shape_0th[0])])
        out_data_1st = np.array([[(S @ rho0[j,k].data_1st + d)
                                  for k in range(rho0.shape_0th[1])]
                                  for j in range(rho0.shape_0th[0])])

    rhof = QGstate(data_2nd = out_data_2nd,
                   data_1st = out_data_1st,
                   data_0th = rho0.data_0th,
                   dims_fls = rho0.dims_fls,
                   dims_cvs = rho0.dims_cvs
                   )
    return rhof


def lindblad_timeevolve(LV: QGsuper,
                        rho0: QGstate,
                        t: float = 1
                        ) -> QGstate:
    """
    ---- Prodcedure ----
    Calculate future state of initial state under evolution from a time-independent Lindbladian. The time evolution is
        ρ(t) = exp[-t*L(·)].ρ(0) 
    where L is the Lindbladian, which may be expressed as
        L(ρ) = -i*[H,ρ] + sum_{j,k} Γ_jk (r_k.ρ.r_j - ½*[r_j.r_k,ρ]_+), where H = ½r.H(2).r + r.H(1) + H(0)
    This is equivalent to the following evolution of the moments of ρ(0)
        Σ(t) = S(t).Σ(0).S(t)^T + V(t),   
        μ(t) = S(t).μ(0) + d(t)
    where for the given Lindbladian L, A = Ω.(H(2) + Im[Γ]) and C = -Ω.Re[Γ].Ω:
        S(t) = exp[t*A],    
        d(t) = (1/A).(exp[t*A] - id).(Ω.H(1)),
        V(t) = ∫_0^t exp[(t-s)*A].C.exp[(t-s)*A^T] ds
             = inv_vec( ∫_0^t exp[(t-s)*A]⊗exp[(t-s)*A].vec(C) ds)
             = inv_vec( ∫_0^t exp[(t-s)*A⊕A].vec(C) ds)  where  A⊕B =  A⊗id + id⊗B
             = inv_vec( (1/(A⊕A).(exp[t*A⊕A] - id).vec(C) ).
    In the above "vec" represents the vectorization operation, where "inv_vec" is the inverse function (column or row 
    stacking can be used here since they both transform the Kronecker product to A⊕A). These are the exact solutions to 
    the differential equations for the moments:
        dΣ(t)/dt = A.Σ(t) + Σ(t).A^T + C,
        dμ(t)/dt = A.μ(t) + d(t).

    ---- Parameters ----
    LV : QGoper
        Time-independent Lindbladian that will control evolution of the state. Must be CVS only and CPTP.
    rho0 : QGstate
        Object on which to apply the dynamical transformation generated by the Lindbladian.
    t : number
        Time at which to stop calculate the future state. Time starts at t=0, default for the future time is t=1.

    ---- Output ----
    rhof : QGstate
        The state evolved under the Lindbladian at the give time.
    """
    if LV.isfls:
        raise ValueError("Generator of open-system evolution cannot have FLS component.")
    if LV.dims_cvs != rho0.dims_cvs:
        raise ValueError("CV component of state and Lindbladian have different dimensions.")
    
    # Construct elements of the open-system transformation
    A = LV.wigner_2nd_deriv_var
    C = LV.wigner_2nd_deriv
    f = LV.wigner_1st_deriv
    S = la.expm(t*A)
    d = t * exp_integrator_phi_function(t*A) @ f
    V = vec_to_mat(t * exp_integrator_phi_function(t*(la.kron(A, np.eye(2*LV.dims_cvs)) 
                                                    + la.kron(np.eye(2*LV.dims_cvs), A)))
                                                    @ mat_to_vec(C), LV.shape_2nd)

    if not rho0.isfls:
        out_data_2nd = S @ rho0.data_2nd @ np.transpose(S) + V
        out_data_1st = S @ rho0.data_1st + d
    else:
        out_data_2nd = np.array([[(S @ rho0[j,k].data_2nd @ np.transpose(S) + V)
                                  for k in range(rho0.shape_0th[1])]
                                  for j in range(rho0.shape_0th[0])])
        out_data_1st = np.array([[(S @ rho0[j,k].data_1st + d)
                                  for k in range(rho0.shape_0th[1])]
                                  for j in range(rho0.shape_0th[0])])

    rhof =  QGstate(data_2nd = out_data_2nd,
                    data_1st = out_data_1st,
                    data_0th = rho0.data_0th,
                    dims_fls = rho0.dims_fls,
                    dims_cvs = rho0.dims_cvs
                    )
    return rhof


def moment_timeevolve(L0: QGsuper = None,
                      Lt: list[tuple[QGsuper,Callable[[float], complex]]] = [],
                      rho0: QGstate = None,
                      tlist: list[float] | npt.NDArray[float] = [0,1],
                      **options
                      ):
    """
    ---- Procedure ----
    Time-dependent solver for the steady-state for a corresponding CV system Liouvillian, which may be time-dependent. 
    The function will output the CV system state at every time specified in tlist. In case the total dynamics is that 
    of a true-quantum state (CPTP) then it is best that each QGsuper also be CPTP. This check is currently performed on
    each element of LT, and will influence the choice of solver. If the total dynamics is not CPTP, then the covariance, 
    means, and norm must all be solved simultaneously, increasing the number of variables that must be handled by the 
    ODE solver. As an example, the following input will result in the non-norm preserving solver being called since the
    ladder operators are not-Hermitian, even though together it is just the dynamics of a Hermitian Hamiltonian:
        LT = [[coherent(create()) , lambda t: np.exp(1j*np.pi*t/2)] , 
              [coherent(destroy()) , lambda t: np.exp(-1j*np.pi*t/2)]].
    The following equivalent statement has no such issue since the QGopers are Hermitian:
        LT = [[coherent(position()) , lambda t: np.sqrt(2)*np.cos(np.pi*t/2)] , 
              [coherent(momentum()) , lambda t: np.sqrt(2)*np.sin(np.pi*t/2)]]
           = [[coherent(create() + destroy()) , lambda t: np.cos(np.pi*t/2)] , 
              [coherent(1j*(create() - destroy())) , lambda t: np.sin(np.pi*t/2)]],

    ---- Parameters ----
    L0 : QGsuper
        Time-independent component of the total Lindbladian/Liouvillian. The Liouvillian need not describe the 
        evolution of a true master equation. Must be CVS-only, and so contain no FLS component.
    Lt : list[tuple[QGsuper,function]]
        The time-dependent component(s) of the total Lindbladian/Liouvillian. Must be passed as a list of two-element
        lists or tuples, where the first element is a QGsuper and the section is the function corresponding to the
        time-dependent coefficient. The function should therefore only accept one argument for the time.
    rho0 : QGstate
        Initial state for the system. Must be a CVS-only state.
    tlist : list[float]
        List of time values at which to store solutions from the state evolution solver. This must be sorted, and
        should contain the start and end times. The default initial and final times are t=[0,1].
    tol : float
        Set tolerance for the magnitude of real or imaginary parts of numbers. Parts of numbers below this
        tolerance value are set to zero.
    **options : 
        Options to be passed to the ODE solver. All options are listed below.
    atol : float
        Absolute tolerance, default value is settings.atol.
    rtol : float
        Relative tolerance, default value is settings.rtol.
    method : str
        Integration method to be used by Scipy solve_ivp. Due to the data used here, only solvers which can handle
        complex values will work. The default is ‘RK45’. Other choices for explicit methods are ‘RK23’ and ‘DOP853’, 
        while for implicit solvers the choice is ‘BDF’.

    ---- Returns ----
    rhot : list[QGstate]
        List of QGstates at the times indicated in tlist.
    """
    # Set options
    defaults = {'atol': qgauss.settings.atol, 'rtol': qgauss.settings.rtol, 'method': 'RK45'}
    options = {**defaults, **options}
    tol = options['atol']

    # Extract data from the initial state
    dims = rho0.dims_cvs
    V0 = symmat_to_vec(rho0.data_2nd)
    m0 = rho0.data_1st
    n0 = rho0.data_0th

    # Extract arrays for the Fokker-Planck equation in Wigner phase-space from L0 and LT. For the time-dependent
    # component, only save those which are non-zero.
    if L0 == None:
        A0, B0, C0 = np.zeros(rho0.shape_2nd), np.zeros(rho0.shape_2nd), np.zeros(rho0.shape_2nd)
        D0, F0 = np.zeros(rho0.shape_1st), np.zeros(rho0.shape_1st)
        G0 = np.zeros(rho0.shape_0th)
    else:
        A0 = L0.wigner_2nd_deriv_var
        B0 = L0.wigner_2nd_var
        C0 = L0.wigner_2nd_deriv
        D0 = L0.wigner_1st_var
        F0 = L0.wigner_1st_deriv
        G0 = L0.wigner_0th

    if Lt == []:
        At, Bt, Ct, Dt, Ft, Gt = [], [], [], [], [], []
    else:
        At = [x for x in Lt if np.all(np.abs(x[0].wigner_2nd_deriv_var) < tol)]
        Bt = [x for x in Lt if np.all(np.abs(x[0].wigner_2nd_var) < tol)]
        Ct = [x for x in Lt if np.all(np.abs(x[0].wigner_2nd_deriv) < tol)]
        Dt = [x for x in Lt if np.all(np.abs(x[0].wigner_1st_var) < tol)]
        Ft = [x for x in Lt if np.all(np.abs(x[0].wigner_1st_deriv) < tol)]
        Gt = [x for x in Lt if np.all(np.abs(x[0].wigner_0th) < tol)]

    # Check if dynamics of the covariances and means do not preverse the norm of the state. Pure dissipation is allowed
    # in the form of a non-zer Gt. The first section will solve the ODEs when the covariances and means are uncoupled, 
    # and the second case will solve them when they are coupled, and hence need to be handled simultaneously.
    if (np.all(np.abs(B0) < tol) 
        and np.all(np.abs(D0) < tol)
        and len(Bt) == 0
        and len(Dt) == 0
        ):
        # Define functions to pass to solve_ivp
        def _ode_func_cov(t,X):
            # Function for the covariance to pass to solve_ivp, which requires vectorization of the symmetric matrix.
            #   dΣ(t)/dt = A.Σ(t) + Σ(t).A^T + C
            A = A0 + sum([x[0]*x[1](t) for x in At])
            C = C0 + sum([x[0]*x[1](t) for x in Ct])
            V = vec_to_symmat(X, 2*dims)
            return symmat_to_vec(A @ V + V @ np.transpose(A) + C)
        
        def _ode_func_mean(t,X):
            # Function for the means to pass to solve_ivp.
            #   dμ(t)/dt = A.μ(t) + F
            A = A0 + sum([x[0]*x[1](t) for x in At])
            F = F0 + sum([x[0]*x[1](t) for x in Ft])
            return A @ X + F
        
        def _ode_func_norm(t,X):
            # Function for the means to pass to solve_ivp. Function is determined by solving
            #   dn(t)/dt = d/dt exp(-v(t)) = exp(-v(t))*(-dv(t)/dt) = -n(t)*G
            G = G0 + sum([x[0]*x[1](t) for x in Gt])
            return -X*G
        
        Vsol = solve_ivp(_ode_func_cov, (tlist[0],tlist[-1]), V0, t_eval = tlist, **options)
        msol = solve_ivp(_ode_func_mean, (tlist[0],tlist[-1]), m0, t_eval = tlist, **options)
        nsol = solve_ivp(_ode_func_norm, (tlist[0],tlist[-1]), n0, t_eval = tlist, **options)

        Vt = [Vsol.y[:,t] for t in range (0,len(tlist))]
        mt = [msol.y[:,t] for t in range(0,len(tlist))]
        nt = [nsol.y[:,t] for t in range(0,len(tlist))]

    else:
        # Define single function to pass to solve_ivp which incorporates the ODEs for all moments. The differential
        # equations are defined as:
        #   dΣ(t)/dt = A.Σ(t) + Σ(t).A^T - Σ(t).B.Σ(t) + C
        #   dμ(t)/dt = (A - B.Σ(t)).μ(t) + F - Σ(t).D
        #   dn(t)/dt = -n(t)*(g + f.μ(t) + ½*μ(t).B.μ(t) + ½*tr[B.Σ(t)])
        def _ode_func_total(t,X):
            A = A0 + sum([x[0]*x[1](t) for x in At])
            B = B0 + sum([x[0]*x[1](t) for x in Bt])
            C = C0 + sum([x[0]*x[1](t) for x in Ct])
            F = F0 + sum([x[0]*x[1](t) for x in Ft])
            D = D0 + sum([x[0]*x[1](t) for x in Dt])
            G = G0 + sum([x[0]*x[1](t) for x in Gt])
            # Split X into leading covariance matrix elements and trailing elements for the mean.
            XV = vec_to_symmat(X[0:dims*(2*dims+1)], 2*dims)
            Xm = X[dims*(2*dims+1):dims*(2*dims+3)]
            Xn = X[dims*(2*dims+3)]
            # Perform matrix/vector operations, convert symmetric covariance matrix back to vector, and append the means.
            return np.concatenate((symmat_to_vec(A @ XV + XV @ np.transpose(A) - XV @ B @ XV + C),
                                   (A - XV @ B) @ Xm + F - XV @ D,
                                   -Xn*(G + F @ Xm + 0.5*Xm @ B @ Xm + 0.5*np.trace(B @ XV))))

        X0 = np.concatenate((V0, m0, n0))
        Xsol = solve_ivp(_ode_func_total, (tlist[0],tlist[-1]), X0, t_eval = tlist, **options)
        
        Vt = [Xsol.y[0:dims*(2*dims+1), t] for t in range (0,len(tlist))]
        mt = [Xsol.y[dims*(2*dims+1):dims*(2*dims+3), t] for t in range (0,len(tlist))]
        nt = [Xsol.y[dims*(2*dims+3), t] for t in range (0,len(tlist))]

    rhot = [QGstate(data_2nd = vec_to_symmat(Vt[t], 2*dims),
                    data_1st = mt[t],
                    data_0th = nt[t],
                    dims_cvs = dims)
                    for t in range(0, len(tlist))]
    return rhot


def backaction_timeevolve(L0: QGsuper = None,
                          Lt: list[tuple[QGsuper,Callable[[float], complex]]] = [],
                          rho0: QGstate = None,
                          tlist: list[float] | npt.NDArray[float] = [0,1],
                          qubit: str = None,
                          **options
                          ):
    """
    ---- Procedure ----
    Time domain solver for the backaction rates of a CV system on a qubit, or a CV system coupled to
    a system of qubits. The function will automatically check if the evolution is Gaussian,
    and will raise an error if not. The component of the qubit state can be specified if the system has an FLS 
    component, and if none is given, the backaction on every component will be solved. If the system is only CV, no 
    qubit state need be specified. The function will return the total time-integrated dephasing and frequency shift, 
    along with instanteous values of the total dephasing and frequency shift, along with the bare, measurement-induced, 
    and parasitic dephasing subcomponents. Each component of the backaction is stored in a single list, where the first
    index corresponds to time. In case the rates for the entire qubit state are calculated, the data in the individual 
    time-slices is of the same format as the output of the steady-state function.

    ---- Parameters ----
    L0 : QGsuper
        Time-independent component of the total Lindbladian/Liouvillian. The Liouvillian need not describe the 
        evolution of a true master equation. Must be CVS-only, and so contain no FLS component.
    Lt : list[tuple[QGsuper,function]]
        The time-dependent component(s) of the total Lindbladian/Liouvillian. Must be passed as a list of two-element
        lists or tuples, where the first element is a QGsuper and the section is the function corresponding to the
        time-dependent coefficient. The function should therefore only accept one argument for the time.
    rho0 : QGstate
        Initial state for the system. Must be a CVS-only state.
    tlist : list[float]
        List of time values at which to store solutions from the state evolution solver. This must be sorted, and
        should contain the start and end times. The default initial and final times are t=[0,1].
    tol : float
        Set tolerance for the magnitude of real or imaginary parts of numbers. Parts of numbers below this
        tolerance value are set to zero.
    qubit : string
        Element of qubit density matrix to solve passed as string, for example, 'e,e' or 'g,e' 
        for a single qubit, 'eg,ee' or 'gg,ge' etc, for a two qubit system. Scales to arbitrary number
        of qubits. If no string is passed the backaction on all elements are solved if the 
        system has an FLS component, or just the steady-state of the CV system if there is not FLS.
        Alternatively, one can use the '1' and '0' in place of 'e' and 'g', respectively.    
    **options : 
        Options to be passed to the ODE solver. All options are listed below.
    atol : float
        Absolute tolerance, default value is settings.atol.
    rtol : float
        Relative tolerance, default value is settings.rtol.
    method : str
        Integration method to be used by Scipy solve_ivp. Due to the data used here, only solvers which can handle
        complex values will work. The default is ‘RK45’. Other choices for explicit methods are ‘RK23’ and ‘DOP853’, 
        while for implicit solvers the choice is ‘BDF’.

    ---- Returns ----
    ba_norm : list[complex] or list[array[complex]]
        Total time-integrated dephasing and frequency shift, as defined by the ratio of the norm with its inital value.
    ba_total : list[complex] or list[array[complex]]
        Steady-state total dephasing and frequency shift.
    ba_bare : list[complex] or list[array[complex]]
        Steady-state parasitic dephasing and frequency shift. Includes components from the innate qubit dynamics
        as well backation from the CVS state which are independent of the first and second moments.
    ba_meas_ind : list[complex] or list[array[complex]]
        Steady-state measurement induced dephasing and frequency shift. This is the component dependent
        on the displacement of the continuous variable system.
    ba_para : list[complex] or list[array[complex]]
        Steady-state parasitic dephasing and frequency shift. The dephasing part of this components arises when the 
        CVS state has variances above vacuum, while the frequency shift is present even for the vacuum shift.
    """
    # Set options
    defaults = {'atol': qgauss.settings.atol, 'rtol': qgauss.settings.rtol, 'method': 'RK45'}
    options = {**defaults, **options}

    # Check and store properties of the total Liouvillian. If L0 is None, then create an empty QQsuper.
    if L0 is None and Lt != []:
        L0 = QGsuper(dims_cvs = Lt[0][0].dims_cvs, 
                     dims_fls = Lt[0][0].dims_fls)
        
    # If rho0 has no FLS component, and the system is FLS, then create a list of CVS states
    if L0.isfls and not rho0.isfls:
        ones = QGstate(data_0th = np.ones((np.prod(L0.dims_fls[0][0]),np.prod(L0.dims_fls[0][1]))),
                       dims_fls = L0.dims_fls[0])
        rho0 = tensor(rho0, ones)

    # ----------------------------------------------------------------------
    # No qubits are present, solve the CV system
    if not L0.isfls and L0.iscvs:
        ba_integrated,ba_total,ba_bare,ba_meas_ind,ba_para = \
            _backaction_timeevolve_solver(L0 = L0, Lt = Lt, rho0 = rho0, tlist = tlist, **options)

    # ----------------------------------------------------------------------
    # Qubit state is specified, solve the corresponding CV component
    elif L0.isfls and qubit is not None:
        # Select index for the qubit state
        qbinary = qubit.replace('e', '1').replace('g', '0')
        qrow = np.prod(L0.dims_fls[0][0]) - int(qbinary.split(',')[0], 2) - 1
        qcol = np.prod(L0.dims_fls[0][1]) - int(qbinary.split(',')[1], 2) - 1
        # Index count is backwards, so 'e...e' is the 0th element and 'g...g' is last
        qindex = np.prod(L0.dims_fls[0][0])*qcol + qrow

        # Check if spin-z Pauli operators are QND-observables, and the dynamics Gaussian
        if L0.issubgauss(qindex) and all([x[0].issubgauss(qindex) for x in Lt]):
            pass
        else:
            sys.exit("Equation of motion for the CV system is not Gaussian. The moment method cannot be used.")

        ba_norm,ba_total,ba_bare,ba_meas_ind,ba_para = \
            _backaction_timeevolve_solver(L0 = L0[qindex,qindex], 
                                          Lt = [[x[0][qindex,qindex],x[1]] for x in Lt], 
                                          rho0 = rho0[qrow,qcol],
                                          tlist = tlist, **options)
        
    # ----------------------------------------------------------------------
    # No qubit state is specified, solve for all components
    elif L0.isfls and qubit is None:
        # Check if spin-z Pauli operators are QND-oberservables, and the dynamics Gaussian
        if L0.isgauss and all([x[0].isgauss for x in Lt]):
            pass
        else:
            sys.exit("Equation of motion for the CV system is not Gaussian. The moment method cannot be used.")
        
        row_total = np.prod(L0.dims_fls[0][0])
        col_total = np.prod(L0.dims_fls[0][1])

        ba_norm = np.empty([len(tlist),row_total,col_total], dtype = complex)
        ba_total = np.empty([len(tlist),row_total,col_total], dtype = complex)
        ba_bare = np.empty([len(tlist),row_total,col_total], dtype = complex)
        ba_meas_ind = np.empty([len(tlist),row_total,col_total], dtype = complex)
        ba_para = np.empty([len(tlist),row_total,col_total], dtype = complex)

        for qrow in range(0,row_total):
            for qcol in range(0,col_total):
                qindex = np.prod(L0.dims_fls[0][0])*qcol + qrow

                (ba_norm[:,qrow,qcol], ba_total[:,qrow,qcol], ba_bare[:,qrow,qcol], 
                 ba_meas_ind[:,qrow,qcol], ba_para[:,qrow,qcol]) = \
                    _backaction_timeevolve_solver(L0 = L0[qindex,qindex], 
                                                  Lt = [[x[0][qindex,qindex],x[1]] for x in Lt], 
                                                  rho0 = rho0[qrow,qcol], 
                                                  tlist = tlist, **options)

    return ba_norm,ba_total,ba_bare,ba_meas_ind,ba_para

 
def _backaction_timeevolve_solver(L0: QGsuper,
                                  Lt: list[tuple[QGsuper,Callable[[float], complex]]],
                                  rho0: QGstate,
                                  tlist: list[float] | npt.NDArray[float],
                                  **options
                                  ):
    """
    The backaction on an operator ρ is defined as tr[ρ] = exp[-v]. The backaction rate is then extracted from dv/dt,
    defined by
        dv/dt = G + μ.D + (1/2)*μ.B.μ + (1/2)*trace[B.Σ]
    where Σ and μ are the 2nd and 1st central moments of ρ, respectively. The elements B,D,G are extracted from the 
    'input' Liouvillian with governs the dynamics of ρ. The dephasing rate and frequency shift correspond to the real 
    and imaginary parts of 'v', respectively. The backaction may be broken into bare/innate 'ba_bare', measurement 
    induced 'ba_meas_ind', and parasitic 'ba_para', components:
        bare = G
        meas_ind = μ.D + (1/2)*μ.B.μ
        para = (1/2)*trace[B.Σ]

    ---- Parameters ----
    L0 : QGsuper
        Time-independent QGsuper whose steady-state is to be solved, and the backaction extracted. Must be CVS-only.
    tol : float
        Set tolerance for the magnitude of real or imaginary parts of numbers. Parts of numbers below this
        tolerance value are set to zero.
    
    ---- Returns ----
    ba_norm : array[complex]
    ba_total : array[complex]
    ba_bare : array[complex]
    ba_meas_ind : array[complex]
    ba_para : array[complex]

    What is the better output format:
    # -> tuple[list[complex],list[complex],list[complex],list[complex],list[complex]] (currently used)
    # -> list[tuple[complex,complex,complex,complex,complex]]
    """
    # Solve the steady-state components of the system evolving under the 'input' QGsuper
    rhot = moment_timeevolve(L0 = L0, Lt = Lt, rho0 = rho0, tlist = tlist, **options)

    # Generate arrays from the QGsuper input
    if L0 == None:
        B0, D0, G0 = np.zeros(rho0.shape_2nd), np.zeros(rho0.shape_1st), np.zeros(rho0.shape_0th)
    else:
        B0 = L0.wigner_2nd_var
        D0 = L0.wigner_1st_var
        G0 = L0.wigner_0th

    if Lt == []:
        Bt, Dt, Gt = [], [], []
    else:
        Bt = [x for x in Lt if np.all(np.abs(x[0].wigner_2nd_var) < tol)]
        Dt = [x for x in Lt if np.all(np.abs(x[0].wigner_1st_var) < tol)]
        Gt = [x for x in Lt if np.all(np.abs(x[0].wigner_0th) < tol)]

    ba_norm = np.empty([len(tlist)], dtype = complex)    
    ba_total = np.empty([len(tlist)], dtype = complex)
    ba_bare = np.empty([len(tlist)], dtype = complex)
    ba_meas_ind = np.empty([len(tlist)], dtype = complex)
    ba_para = np.empty([len(tlist)], dtype = complex)

    # Calculate the parasitic and measurement induced parts of the backaction
    for u in range(0,len(tlist)):
        B = B0 + sum([x[0]*x[1](tlist[u]) for x in Bt])
        D = D0 + sum([x[0]*x[1](tlist[u]) for x in Dt])
        G = G0 + sum([x[0]*x[1](tlist[u]) for x in Gt])

        ba_norm[u] = rhot[u].data_0th/rhot[0].data_0th
        ba_bare[u] = G
        ba_meas_ind[u] = rhot[u].data_1st @ D + 0.5*rhot[u].data_1st @ B @ rhot[u].data_1st
        ba_para[u] = 0.5*np.trace(B @ rhot[u].data_2nd)
        ba_total[u] = ba_bare[u] + ba_meas_ind[u] + ba_para[u]

    return ba_norm,ba_total,ba_bare,ba_meas_ind,ba_para